title: GongMH's Blog
email: gongmh_work@126.com

github: gongmh

baseurl: "/blog" 

timezone: Asia/Shanghai

categories_conf: [
  # ["lnmp", "LNMP", "/posts/lnmp.html"], 
  # ["java", "Java", "/posts/java.html"],
  # ["source", "开源学习", "/posts/open_source.html"], 
  ["about", "关于", "/about"]
]

# Build settings
markdown: kramdown

# code high light
highlighter: pygments
highlight: true

# 分页
paginate: 10
paginate_path: "page:num"

plugins:
 - jekyll-paginate

