# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 博客
brief-intro: 记录生活，记录工作。
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://www.gongmh.com" # the base hostname & protocol for your site
timezone: Asia/Shanghai

permalink: /:year/:month/:day/:title/

# other links
github_username: gongmh
email: pandergong@gmail.com

description_footer: 记录生活，记录工作。

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #hygblog
disqus_shortname: blog-klfcgrluvm

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 96b386d0a9ddef338160cb66102a17b5

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
port: 4000

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6

# google adsense
google_adsense: ca-pub-4035145038623503